DROP DATABASE IF EXISTS bots;
CREATE DATABASE bots;

DROP TABLE IF EXISTS user
DROP TABLE IF EXISTS bot
DROP TABLE IF EXISTS has_bot

CREATE TABLE user (
    id INT NOT NULL AUTOINCREMENT,
    username VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
);

CREATE TABLE bot (
    id INT NOT NULL,
    user_id INT NOT NULL,
    name VARCHAR(255),
    file_path VARCHAR(255),
    PRIMARY KEY (id),
);

ALTER TABLE bot
ADD CONSTRAINT fk_user_id
FOREIGN KEY (user_id) REFERENCES user(id)
ON DELETE CASCADE
